#! /bin/bash

# TheParkerLab
# Vivek Rai
# GPLv3

[[ -z $1 ]] && echo "Usage: PROG <BED-file>\nWrites to STDOUT." && exit

awk 'BEGIN {NUM=0} {print (NUM+1)"\t"$0"\t-"; NUM=NUM+1}' $1 | sort -k2,2 -k3n
