#! /usr/bin/env ruby

# TheParkerLab
# Vivek Rai
# GPLv3

(puts 'Usage: PROG <URLs>'; exit) unless ARGV[0]

ARGV.each_with_index do |u, i|
  url = u.gsub('hgTracks', 'hgRenderTracks')
  `curl -# '#{url}' -o screenshot_#{i}.png`
end

