#! /bin/bash

# TheParkerLab
# Vivek rai
# GPLv3

echo "Filters peak for FDR < 0.05, merges and sorts final BED output" >&2
echo "Reads from FILE or STDIN; writes to STDOUT" >&2

PROG=cat

if [[ $1 =~ \.gz$  ]]; then
  PROG=zcat
fi

$PROG ${1:-/dev/stdin} \
  | awk '{if($9>=1.30102999566){print}}' \
  | sort -k1,1 -k2,2n \
  | bedtools merge \
  | sort -k1,1 -k2,2n
