#! /usr/bin/env python

import sys
import yaml


def jsontoyaml(file):
  with open(file, 'r') as f:
    _yaml = yaml.load(f)
    sys.stdout.write(yaml.dump(_yaml, default_flow_style=False, indent=4))


if __name__ == '__main__':
  if len(sys.argv) < 2:
    print("Usage: json2yaml <input.json>\nWrites to STDOUT.")
    sys.exit(1)
  jsontoyaml(sys.argv[1])
