#! /usr/bin/env python

import sys
import yaml
import argh
import os


def jsontoyaml(input):
    """ Convert JSON to YAML.

    Specify FILE or input from STDIN.
    """
    if not os.path.exists(input):
        print("File not found.")
        sys.exit(1)
        with open(input, 'r') as f:
            _yaml = yaml.load(f)
    print(yaml.dump(_yaml, default_flow_style=False, indent=4))


if __name__ == '__main__':
    argh.dispatch_command(jsontoyaml)
